#
# Makefile
# drewtg, 2020-05-03 03:41
#

all:
	@echo "Makefile needs your attention"
create: create_store.py add_data.py
				python3 create_store.py 
				python3 add_data.py
clear: shoestore.db
				rm shoestore.db
# vim:ft=make

